import type { Request, Response } from "express";

export const getCities = (req: Request, res: Response) => {
  const { search } = req.query;
  //filter ignore diacritics and casing
  if (!search) return res.status(200).json(cities);
  const filteredCities = cities.filter((city) =>
    city
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .includes(
        search
          .toString()
          .toLowerCase()
          .normalize("NFD")
          .replace(/[\u0300-\u036f]/g, "")
      )
  );
  //only return top 20 results
  return res.status(200).json({ cities: filteredCities.slice(0, 20) });
};

const cities = [
  "Adamov",
  "Albrechtice",
  "Arnoltice",
  "As",
  "Babice",
  "Banov",
  "Baska",
  "Batelov",
  "Bavory",
  "Bechyne",
  "Bela pod Bezdezem",
  "Belotin",
  "Benatky nad Jizerou",
  "Benesov",
  "Benesovice",
  "Bernartice",
  "Bernartice nad Odrou",
  "Beroun",
  "Bezdekov",
  "Bilina",
  "Bilovice",
  "Bilovice nad Svitavou",
  "Bitovany",
  "Blansko",
  "Blatna",
  "Blizevedly",
  "Blovice",
  "Blucina",
  "Bludov",
  "Bludovice",
  "Bochov",
  "Bohumin",
  "Bohunovice",
  "Bojanov",
  "Bojkovice",
  "Bolatice",
  "Bolebor",
  "Bor",
  "Boretice",
  "Borohradek",
  "Borotin",
  "Borovany",
  "Borsice",
  "Bosin",
  "Boskovice",
  "Bradlec",
  "Brandys nad Labem-Stara Boleslav",
  "Branky",
  "Branov",
  "Bratrikov",
  "Brezi",
  "Brezno",
  "Brezolupy",
  "Brezova",
  "Brno",
  "Brod",
  "Brodce",
  "Brodek",
  "Broumov",
  "Brtnice",
  "Bruntal",
  "Brusperk",
  "Bucovice",
  "Budyne nad Ohri",
  "Bukovec",
  "Bustehrad",
  "Bylnice",
  "Bystrice",
  "Bystrice nad Pernstejnem",
  "Bystrice pod Hostynem",
  "Cakovice",
  "Caslav",
  "Cebin",
  "Cechtice",
  "Cejc",
  "Cejkovice",
  "Celadna",
  "Celakovice",
  "Cepi",
  "Cercany",
  "Cerekvice nad Loucnou",
  "Cerhenice",
  "Cerna Hora",
  "Cerna za Bory",
  "Cerncice",
  "Cernosice",
  "Cernotin",
  "Cervene Pecky",
  "Cerveny Kostelec",
  "Ceska",
  "Ceska Skalice",
  "Ceska Trebova",
  "Ceska Ves",
  "Ceske Mezirici",
  "Cesky Brod",
  "Cesky Dub",
  "Cestice",
  "Cheb",
  "Cheznovice",
  "Chlumcany",
  "Chlumec",
  "Chlumec nad Cidlinou",
  "Chlupice",
  "Chocen",
  "Chocerady",
  "Chodov",
  "Chodova Plana",
  "Chomutov",
  "Chotebor",
  "Chotesov",
  "Chotetov",
  "Chotoviny",
  "Choustnik",
  "Choustnikovo Hradiste",
  "Chrast",
  "Chrastna",
  "Chribska",
  "Chroustovice",
  "Chrudim",
  "Chvalec",
  "Chyne",
  "Cista",
  "Citoliby",
  "Citov",
  "Ckyne",
  "Ctidruzice",
  "Cvikov",
  "Dalovice",
  "Damnice",
  "Darkovicky",
  "Davle",
  "Deblin",
  "Dehylov",
  "Dejvice",
  "Desna",
  "Detmarovice",
  "Dily",
  "Divisov",
  "Dlouha Trebova",
  "Dlouhe",
  "Dobra",
  "Dobra Voda",
  "Dobrany",
  "Dobre",
  "Dobrichovice",
  "Dobris",
  "Dobriv",
  "Dobronin",
  "Dobroslavice",
  "Dobruska",
  "Doksy",
  "Dolany",
  "Dolni Becva",
  "Dolni Benesov",
  "Dolni Berkovice",
  "Dolni Bojanovice",
  "Dolni Brezany",
  "Dolni Dunajovice",
  "Dolni Jircany",
  "Dolni Kounice",
  "Dolni Nemci",
  "Dolni Poustevna",
  "Dolni Radechova",
  "Dolni Sucha",
  "Dolni Sytova",
  "Dolni Terlicko",
  "Dolni Zandov",
  "Domasov",
  "Domazelice",
  "Domazlice",
  "Doubravnik",
  "Doubravy",
  "Doudleby nad Orlici",
  "Drahotuse",
  "Drisy",
  "Drnovice",
  "Drzkov",
  "Drzovice",
  "Dubec",
  "Dubenec",
  "Dubi",
  "Dubicko",
  "Dubnany",
  "Dubne",
  "Duchcov",
  "Dukovany",
  "Dusejov",
  "Dvorce",
  "Dvur Kralove nad Labem",
  "Dymokury",
  "Ejpovice",
  "Filipova",
  "Francova Lhota",
  "Frantiskovy Lazne",
  "Frenstat pod Radhostem",
  "Frydek-Mistek",
  "Frydlant",
  "Frydlant nad Ostravici",
  "Frystak",
  "Fulnek",
  "Golcuv Jenikov",
  "Grucovice",
  "Habartov",
  "Haj ve Slezsku",
  "Haje",
  "Hajnice",
  "Halenkov",
  "Hamr",
  "Harrachov",
  "Havrice",
  "Hermanuv Mestec",
  "Hlasna Treban",
  "Hlinsko",
  "Hlubocepy",
  "Hlubocky",
  "Hluboka nad Vltavou",
  "Hlucin",
  "Hodice",
  "Hodslavice",
  "Holasice",
  "Holesov",
  "Holice",
  "Holoubkov",
  "Holubice",
  "Holysov",
  "Horesedly",
  "Horice",
  "Horin",
  "Horni Becva",
  "Horni Benesov",
  "Horni Bojanovice",
  "Horni Briza",
  "Horni Lutyne",
  "Horni Nemci",
  "Horni Pocernice",
  "Horni Podluzi",
  "Horni Redice",
  "Horni Slavkov",
  "Horomerice",
  "Horousanky",
  "Horovice",
  "Horsovsky Tyn",
  "Hospozin",
  "Hosteradice",
  "Hostice",
  "Hostin",
  "Hostinne",
  "Hostivice",
  "Hostomice",
  "Hovezi",
  "Hovorany",
  "Hovorcovice",
  "Hrabetice",
  "Hradcovice",
  "Hradec",
  "Hradec nad Moravici",
  "Hradek",
  "Hradek nad Nisou",
  "Hradiste",
  "Hranice",
  "Hrdejovice",
  "Hronov",
  "Hrusovany nad Jevisovkou",
  "Hrusovany u Brna",
  "Hudlice",
  "Hukvaldy",
  "Hulin",
  "Humpolec",
  "Hustopece",
  "Hvozd",
  "Hysly",
  "Ivancice",
  "Ivanovice na Hane",
  "Jablonec nad Nisou",
  "Jablonne nad Orlici",
  "Jablonne v Podjestedi",
  "Jablunka",
  "Jablunkov",
  "Jalubi",
  "Janovice",
  "Janovice nad Uhlavou",
  "Jaromer",
  "Jaroslav",
  "Jaroslavice",
  "Jedovnice",
  "Jenec",
  "Jesenice",
  "Jesenik",
  "Jevicko",
  "Jevisovice",
  "Jezov",
  "Jihlava",
  "Jilemnice",
  "Jilove u Prahy",
  "Jilovec",
  "Jiloviste",
  "Jince",
  "Jindrichuv Hradec",
  "Jinocany",
  "Jirice",
  "Jirickov",
  "Jirkov",
  "Jirny",
  "Jistebnik",
  "Kacerov",
  "Kacice",
  "Kadan",
  "Kamenice",
  "Kamenicky Senov",
  "Kamenne Zehrovice",
  "Kamenny Privoz",
  "Kamyk",
  "Kaplice",
  "Karlin",
  "Karlovy Vary",
  "Karvina",
  "Kaznejov",
  "Kbely",
  "Kdyne",
  "Kladno",
  "Klasterec nad Ohri",
  "Klatovy",
  "Klecany",
  "Klicany",
  "Klimkovice",
  "Klobouky",
  "Knezmost",
  "Kochovice",
  "Koci",
  "Kolodeje",
  "Komarice",
  "Komorni Lhotka",
  "Konice",
  "Kopidlno",
  "Koprivnice",
  "Korycany",
  "Kosmonosy",
  "Kostelec na Hane",
  "Kostelec nad Cernymi Lesy",
  "Kostelec nad Labem",
  "Kostelec nad Orlici",
  "Kostelni Hlavno",
  "Kostice",
  "Kotencice",
  "Kourim",
  "Kouty",
  "Kozmice",
  "Kralice na Hane",
  "Kraliky",
  "Kralovice",
  "Kralupy nad Vltavou",
  "Kraluv Dvur",
  "Kraslice",
  "Krasna Hora nad Vltavou",
  "Krasna Lipa",
  "Kratonohy",
  "Kravare",
  "Krchleby",
  "Krenovice",
  "Krepenice",
  "Kresice",
  "Kretin",
  "Krhova",
  "Krivoklat",
  "Krizanov",
  "Krmelin",
  "Krnov",
  "Krnsko",
  "Krouna",
  "Krtiny",
  "Krumvir",
  "Krupka",
  "Ktis",
  "Kuncice",
  "Kuncina",
  "Kunovice",
  "Kunratice",
  "Kunstat",
  "Kurim",
  "Kvetnice",
  "Kyjov",
  "Kylesovice",
  "Lachov",
  "Ladvi",
  "Lampertice",
  "Lanskroun",
  "Lanzhot",
  "Lasenice",
  "Lazne Bohdanec",
  "Lazne Libverda",
  "Ledec nad Sazavou",
  "Lednice",
  "Leskovec",
  "Lesonice",
  "Letohrad",
  "Letovice",
  "Lety",
  "Lhota",
  "Lhota pod Libcany",
  "Lhotka",
  "Liban",
  "Libcany",
  "Liberec",
  "Libesice",
  "Libeznice",
  "Libice nad Cidlinou",
  "Libis",
  "Libocany",
  "Libochovicky",
  "Libos",
  "Lichkov",
  "Lichnov (o. Novy Jicin)",
  "Line",
  "Lipence",
  "Lipnik nad Becvou",
  "Lipova",
  "Lisov",
  "Litava",
  "Liten",
  "Litovel",
  "Litvinov",
  "Lodenice",
  "Loket",
  "Lomnice",
  "Lomnice nad Luznici",
  "Lomnice nad Popelkou",
  "Loucany",
  "Loucen",
  "Loukov",
  "Lounovice pod Blanikem",
  "Louny",
  "Lovosice",
  "Lubenec",
  "Luby",
  "Luhacovice",
  "Luka",
  "Lukov",
  "Lustenice",
  "Lutin",
  "Luze",
  "Luzna",
  "Lysa nad Labem",
  "Lysice",
  "Mala Skala",
  "Malcice",
  "Malenice",
  "Malenovice",
  "Malesov",
  "Maly Ujezd",
  "Marianska",
  "Markvartovice",
  "Marov u Upice",
  "Mcely",
  "Mechenice",
  "Menany",
  "Merklin",
  "Mesice",
  "Mestec",
  "Mesto Touskov",
  "Mezibori",
  "Mezilesi",
  "Michle",
  "Mikulov",
  "Mikulovice",
  "Milevsko",
  "Milikov",
  "Milin",
  "Milonice",
  "Milotice",
  "Milovice",
  "Mimon",
  "Miroslav",
  "Mirosov",
  "Mirosovice",
  "Mlada Vozice",
  "Mlade Buky",
  "Mladkov",
  "Mlazovice",
  "Mnichovice",
  "Mnisek pod Brdy",
  "Modrice",
  "Mohelnice",
  "Mokra Horakov",
  "Mokrany",
  "Moran",
  "Moravicany",
  "Moravska Nova Ves",
  "Moravska Trebova",
  "Moravske Budejovice",
  "Moravsky Beroun",
  "Moravsky Krumlov",
  "Moravsky Pisek",
  "Moravsky Zizkov",
  "Most",
  "Mostek",
  "Mosty u Jablunkova",
  "Mratin",
  "Mrlinek",
  "Msec",
  "Mseno",
  "Mukarov",
  "Mutenice",
  "Nachod",
  "Naklo",
  "Napajedla",
  "Nasavrky",
  "Navsi u Jablunkova",
  "Nechanice",
  "Nedakonice",
  "Nedomice",
  "Nedvedice",
  "Nehvizdy",
  "Nejdek",
  "Nelahozeves",
  "Nenkovice",
  "Nepomysl",
  "Neratovice",
  "Nesovice",
  "Nezamyslice",
  "Nezvestice",
  "Nikolcice",
  "Nivnice",
  "Nova Cerekev",
  "Nova Lhota",
  "Nova Paka",
  "Nova Vcelnice",
  "Nova Ves",
  "Nove Dvory",
  "Nove Mesto na Morave",
  "Nove Mesto nad Metuji",
  "Nove Straseci",
  "Nove Veseli",
  "Novosedly",
  "Novy Bor",
  "Novy Bydzov",
  "Novy Hrozenkov",
  "Novy Jicin",
  "Novy Knin",
  "Novy Oldrichov",
  "Nucice",
  "Nupaky",
  "Nydek",
  "Nymburk",
  "Nyrany",
  "Nyrsko",
  "Obrany",
  "Obristvi",
  "Ochoz",
  "Odolena Voda",
  "Odry",
  "Ohrobec",
  "Okrisky",
  "Olomouc",
  "Olomucany",
  "Olovi",
  "Olsany",
  "Ondrejov",
  "Oparany",
  "Opatovice nad Labem",
  "Opava",
  "Opocno",
  "Orlova",
  "Osecna",
  "Osek",
  "Osik",
  "Oslavany",
  "Ostopovice",
  "Ostrava",
  "Ostromer",
  "Ostrov",
  "Ostrov u Macochy",
  "Ostrozska Lhota",
  "Ostrozska Nova Ves",
  "Otnice",
  "Otrokovice",
  "Pacov",
  "Palkovice",
  "Pardubice",
  "Pariz",
  "Pavlice",
  "Pchery",
  "Pecin",
  "Pecky",
  "Pelhrimov",
  "Perstejn",
  "Petrovice",
  "Petrovice u Karvine",
  "Petrvald",
  "Pilsen",
  "Pisecna",
  "Pistovice",
  "Plana",
  "Planany",
  "Plouznice",
  "Pocatky",
  "Pocenice",
  "Podborany",
  "Podebrady",
  "Podivin",
  "Polepy",
  "Polesovice",
  "Police nad Metuji",
  "Policka",
  "Polna",
  "Poricany",
  "Poritsch",
  "Postoloprty",
  "Postrelmov",
  "Potstejn",
  "Prachatice",
  "Prackovice nad Labem",
  "Prague",
  "Prazmo",
  "Preckov",
  "Predklasteri",
  "Predmerice nad Jizerou",
  "Predmerice nad Labem",
  "Predmesti",
  "Prelouc",
  "Prepere",
  "Prerov nad Labem",
  "Prestice",
  "Prezletice",
  "Pribor",
  "Pribyslav",
  "Prikazy",
  "Primda",
  "Prlov",
  "Prosetin",
  "Protivin",
  "Provodov",
  "Pruhonice",
  "Prusanky",
  "Psary",
  "Pustejov",
  "Pysely",
  "Radim",
  "Radnice",
  "Radostice",
  "Radostin",
  "Radun",
  "Raj",
  "Rajec-Jestrebi",
  "Rajecko",
  "Rakovnik",
  "Rapotice",
  "Rapotin",
  "Raspenava",
  "Rataje",
  "Ratibor",
  "Ratiskovice",
  "Rebesovice",
  "Repy",
  "Ricany",
  "Rikovice",
  "Ritka",
  "Rokycany",
  "Rokytnice",
  "Rokytnice nad Jizerou",
  "Ronov nad Doubravou",
  "Rosice",
  "Roudnice nad Labem",
  "Roudnicek",
  "Rousinov",
  "Rovensko pod Troskami",
  "Rovina",
  "Rovna",
  "Rozdrojovice",
  "Rozmital pod Tremsinem",
  "Roznov pod Radhostem",
  "Rozsochatec",
  "Roztoky",
  "Rtyne",
  "Ruda nad Moravou",
  "Rudikov",
  "Rudna",
  "Rudolfov",
  "Rudoltice",
  "Rybna",
  "Rychnov",
  "Rychnov nad Kneznou",
  "Rychvald",
  "Rymarov",
  "Sadska",
  "Sanov",
  "Sany",
  "Satov",
  "Seberov",
  "Sebrov",
  "Sedlcany",
  "Sedlec",
  "Sedliste",
  "Seibersdorf",
  "Semily",
  "Senec",
  "Senice na Hane",
  "Senohraby",
  "Senov",
  "Sestajovice",
  "Sezemice",
  "Sibrina",
  "Silherovice",
  "Siluvky",
  "Sivice",
  "Skalice",
  "Skalsko",
  "Skripov",
  "Skuhrov nad Belou",
  "Skutec",
  "Slany",
  "Slapanice",
  "Slapy",
  "Slavicin",
  "Slavkov u Brna",
  "Slavonice",
  "Sloup",
  "Sluknov",
  "Slusovice",
  "Smirice",
  "Smrzovka",
  "Snedovice",
  "Snezne",
  "Sobeslav",
  "Sobotka",
  "Sokolov",
  "Spalene Porici",
  "Spytihnev",
  "Stalkov",
  "Stankov",
  "Stara Paka",
  "Stara Voda",
  "Stare Mesto",
  "Stare Sedliste",
  "Starec",
  "Starovice",
  "Starovicky",
  "Stary Bydzov",
  "Statenice",
  "Stenovice",
  "Stepanov",
  "Sterboholy",
  "Sternberk",
  "Steti",
  "Stezery",
  "Stitina",
  "Stity",
  "Stochov",
  "Stod",
  "Stoky",
  "Strachotice",
  "Strachotin",
  "Strakonice",
  "Strancice",
  "Strasice",
  "Straz nad Nisou",
  "Straz pod Ralskem",
  "Strazek",
  "Straznice",
  "Strelice",
  "Stribrec",
  "Stribrna Skalice",
  "Stribro",
  "Stritez nad Ludinou",
  "Strunkovice nad Blanici",
  "Studenka",
  "Sucha Loz",
  "Sudkov",
  "Sumice",
  "Sumperk",
  "Susice",
  "Svatava",
  "Svaty Jan nad Malsi",
  "Svetla nad Sazavou",
  "Sviadnov",
  "Svihov",
  "Svitavka",
  "Svitavy",
  "Svojek",
  "Svojkov",
  "Syrovice",
  "Tachlovice",
  "Tachov",
  "Tehov",
  "Telc",
  "Telnice",
  "Temice",
  "Teplice",
  "Tesetice",
  "Tetin",
  "Tisice",
  "Tisnov",
  "Tlumacov",
  "Tman",
  "Tosovice",
  "Trebechovice pod Orebem",
  "Trebestovice",
  "Trebon",
  "Tremesna",
  "Tremosna",
  "Trhovy Stepanov",
  "Trinec",
  "Trmice",
  "Troja",
  "Trstenice",
  "Trutnov",
  "Tucapy",
  "Tuchlovice",
  "Tuchomerice",
  "Tupesy",
  "Turnov",
  "Tursko",
  "Tvarozna",
  "Tvrdonice",
  "Tynec nad Sazavou",
  "Tyniste nad Orlici",
  "Uhersky Brod",
  "Uhersky Ostroh",
  "Uhonice",
  "Uhrice",
  "Ujezd",
  "Ujezd nad Lesy",
  "Unetice",
  "Unicov",
  "Usti nad Orlici",
  "Ustin",
  "Uvaly",
  "Uzice",
  "Vacenovice",
  "Valasske Klobouky",
  "Valasske Mezirici",
  "Valtice",
  "Vamberk",
  "Varnsdorf",
  "Vcelna",
  "Velehrad",
  "Velesin",
  "Velesovice",
  "Velka Bites",
  "Velka Bystrice",
  "Velka Dobra",
  "Velka Jesenice",
  "Velka Polom",
  "Velke Albrechtice",
  "Velke Brezno",
  "Velke Heraltice",
  "Velke Hydcice",
  "Velke Losiny",
  "Velke Mezirici",
  "Velke Opatovice",
  "Velke Popovice",
  "Velke Prilepy",
  "Velke Svatonovice",
  "Velky",
  "Velky Borek",
  "Velky Osek",
  "Veltrusy",
  "Velvary",
  "Vendryne",
  "Vernovice",
  "Veseli nad Luznici",
  "Veseli nad Moravou",
  "Veverska Bityska",
  "Veverske Kninice",
  "Vidce",
  "Vimperk",
  "Vinarice",
  "Vinicne Sumice",
  "Visnove",
  "Vitkov",
  "Vizovice",
  "Vlachovice",
  "Vladislav",
  "Vlasim",
  "Vlastislav",
  "Vlcovice",
  "Vochov",
  "Vodnany",
  "Vojkovice",
  "Volyne",
  "Votice",
  "Vracov",
  "Vrane nad Vltavou",
  "Vratimov",
  "Vratkov",
  "Vrbice",
  "Vrbno pod Pradedem",
  "Vrchlabi",
  "Vresina",
  "Vsechovice",
  "Vselibice",
  "Vsenory",
  "Vsestary",
  "Vsetaty",
  "Vsetin",
  "Vtelno",
  "Vyprachtice",
  "Vysker",
  "Vysoka",
  "Vysoka nad Labem",
  "Vysoke Myto",
  "Vysoke Veseli",
  "Zabcice",
  "Zabreh",
  "Zadni Treban",
  "Zajeci",
  "Zamberk",
  "Zampach",
  "Zandov",
  "Zasova",
  "Zatcany",
  "Zborovice",
  "Zbuch",
  "Zbysov",
  "Zdanice",
  "Zdeslav",
  "Zdiby",
  "Zdice",
  "Zdirec",
  "Zdounky",
  "Zehun",
  "Zelenec",
  "Zelenka",
  "Zelesice",
  "Zeletava",
  "Zeleznice",
  "Zelezny Brod",
  "Zeliv",
  "Zeravice",
  "Zidlochovice",
  "Zilina",
  "Zipotin",
  "Zizkov",
  "Zlata",
  "Zlate Hory",
  "Zlicin",
  "Zliv",
  "Znojmo",
  "Zubri",
  "Zulova",
  "Zvole",
  "Bakov nad Jizerou",
  "Bělá pod Bezdězem",
  "Benátky nad Jizerou",
  "Benešov",
  "Bohutín",
  "Brandýs nad Labem-Stará Boleslav",
  "Brandýsek",
  "Březnice",
  "Buštěhrad",
  "Byšice",
  "Bystřice",
  "Čáslav",
  "Čechtice",
  "Čelákovice",
  "Čerčany",
  "Černošice",
  "Červené Pečky",
  "Český Brod",
  "Chyňava",
  "Církvice",
  "Cítov",
  "Divišov",
  "Dobřichovice",
  "Dobříš",
  "Dobrovice",
  "Dolní Beřkovice",
  "Dolní Bousov",
  "Dolní Břežany",
  "Horní Počaply",
  "Horoměřice",
  "Hořovice",
  "Hovorčovice",
  "Hradištko",
  "Hřebeč",
  "Hýskov",
  "Jeneč",
  "Jílové u Prahy",
  "Kačice",
  "Kamenné Žehrovice",
  "Kamenný Přívoz",
  "Klobuky",
  "Kněžmost",
  "Kolín",
  "Komárov",
  "Kosova Hora",
  "Kostelec nad Černými Lesy",
  "Kouřim",
  "Králův Dvůr",
  "Krásná Hora nad Vltavou",
  "Křinec",
  "Kutná Hora",
  "Lány",
  "Libčice nad Vltavou",
  "Líbeznice",
  "Libiš",
  "Libušín",
  "Lochovice",
  "Loděnice",
  "Loučeň",
  "Luštěnice",
  "Lužec nad Vltavou",
  "Lužná",
  "Lysá nad Labem",
  "Mělník",
  "Měšice",
  "Městec Králové",
  "Milín",
  "Mladá Boleslav",
  "Mnichovo Hradiště",
  "Mníšek pod Brdy",
  "Mšeno",
  "Mukařov",
  "Načeradec",
  "Netvořice",
  "Neveklov",
  "Nižbor",
  "Nové Strašecí",
  "Nový Knín",
  "Obecnice",
  "Ondřejov",
  "Pavlíkov",
  "Pečky",
  "Plaňany",
  "Poděbrady",
  "Poříčany",
  "Poříčí nad Sázavou",
  "Postupice",
  "Přerov nad Labem",
  "Příbram",
  "Průhonice",
  "Psáry",
  "Pyšely",
  "Rakovník",
  "Řevnice",
  "Řevničov",
  "Řež",
  "Říčany",
  "Rožďalovice",
  "Rožmitál pod Třemšínem",
  "Rudná",
  "Sadská",
  "Sázava",
  "Sedlčany",
  "Šestajovice",
  "Slaný",
  "Smečno",
  "Stará Huť",
  "Starý Kolín",
  "Štěchovice",
  "Strančice",
  "Suchdol",
  "Tišice",
  "Třebotov",
  "Trhový Štěpánov",
  "Tuchoměřice",
  "Týnec nad Labem",
  "Týnec nad Sázavou",
  "Uhlířské Janovice",
  "Unhošť",
  "Úvaly",
  "Velim",
  "Velká Dobrá",
  "Velké Popovice",
  "Velké Přílepy",
  "Velký Osek",
  "Veltruby",
  "Vestec",
  "Vinařice",
  "Vlašim",
  "Vrané nad Vltavou",
  "Vrdy",
  "Všenory",
  "Všetaty",
  "Zaječov",
  "Zásmuky",
  "Zbraslavice",
  "Žďár",
  "Žebrák",
  "Zeleneč",
  "Žiželice",
  "Žleby",
  "Zlonice",
  "Zruč nad Sázavou",
  "Albrechtice nad Orlicí",
  "Bílá Třemešná",
  "Borohrádek",
  "Častolovice",
  "Černilov",
  "Černožice",
  "Červený Kostelec",
  "Česká Skalice",
  "České Meziříčí",
  "Dobruška",
  "Dolní Černilov",
  "Doudleby nad Orlicí",
  "Dvůr Králové nad Labem",
  "Hořice",
  "Hostinné",
  "Hradec Králové",
  "Jaroměř",
  "Jičín",
  "Kostelec nad Orlicí",
  "Kvasiny",
  "Lázně Bělohrad",
  "Libáň",
  "Machov",
  "Malé Svatoňovice",
  "Meziměstí",
  "Mladé Buky",
  "Náchod",
  "Nová Paka",
  "Nové Město nad Metují",
  "Nový Bydžov",
  "Opočno",
  "Ostroměř",
  "Pecka",
  "Pilníkov",
  "Police nad Metují",
  "Předměřice nad Labem",
  "Provodov-Šonov",
  "Radvanice",
  "Rokytnice v Orlických Horách",
  "Rtyně v Podkrkonoší",
  "Rudník",
  "Rychnov nad Kněžnou",
  "Skuhrov nad Bělou",
  "Smidary",
  "Smiřice",
  "Solnice",
  "Špindlerův Mlýn",
  "Stará Paka",
  "Staré Nechanice",
  "Stěžery",
  "Svoboda nad Úpou",
  "Teplice nad Metují",
  "Třebechovice pod Orebem",
  "Týniště nad Orlicí",
  "Úpice",
  "Valdice",
  "Velké Poříčí",
  "Velké Svatoňovice",
  "Vrchlabí",
  "Všestary",
  "Žacléř",
  "Zadní Mostek",
  "Železnice",
  "Abertamy",
  "Aš",
  "Březová",
  "Bukovany",
  "Dolní Rychnov",
  "Dolní Žandov",
  "Františkovy Lázně",
  "Hazlov",
  "Horní Slavkov",
  "Hroznětín",
  "Jáchymov",
  "Klášter",
  "Kynšperk nad Ohří",
  "Lázně Kynžvart",
  "Mariánské Lázně",
  "Merklín",
  "Město",
  "Nová Role",
  "Nové Sedlo",
  "Oloví",
  "Plesná",
  "Rotava",
  "Sadov",
  "Skalná",
  "Toužim",
  "Velká Hleďsebe",
  "Vintířov",
  "Žlutice",
  "Benecko",
  "Brniště",
  "Česká Lípa",
  "Český Dub",
  "Chrastava",
  "Desná",
  "Dubá",
  "Frýdlant",
  "Hejnice",
  "Hodkovice nad Mohelkou",
  "Horní Branná",
  "Hrádek nad Nisou",
  "Jablonec nad Jizerou",
  "Jablonné v Podještědí",
  "Janov nad Nisou",
  "Josefův Důl",
  "Kamenický Šenov",
  "Kořenov",
  "Košťálov",
  "Lučany nad Nisou",
  "Malá Skála",
  "Mimoň",
  "Mníšek",
  "Nové Město pod Smrkem",
  "Nový Bor",
  "Ohrazenice",
  "Osečná",
  "Pěnčín",
  "Plavy",
  "Poniklá",
  "Příšovice",
  "Smržovka",
  "Stráž nad Nisou",
  "Stráž pod Ralskem",
  "Studenec",
  "Tanvald",
  "Velké Hamry",
  "Višňova",
  "Vysoké nad Jizerou",
  "Zákupy",
  "Žandov",
  "Železný Brod",
  "Bartošovice",
  "Baška",
  "Bílovec",
  "Bohumín",
  "Bohuslavice",
  "Brantice",
  "Břidličná",
  "Brumovice",
  "Bruntál",
  "Brušperk",
  "Budišov nad Budišovkou",
  "Čeladná",
  "Český Těšín",
  "Chlebičov",
  "Chotěbuz",
  "Chuchelná",
  "Darkovice",
  "Dětmarovice",
  "Dobrá",
  "Dobratice",
  "Dolní Benešov",
  "Dolní Lhota",
  "Dolní Lutyně",
  "Dolní Životice",
  "Doubrava",
  "Frenštát pod Radhoštěm",
  "Fryčovice",
  "Frýdek-Místek",
  "Frýdlant nad Ostravicí",
  "Háj ve Slezsku",
  "Hať",
  "Havířov",
  "Hlučín",
  "Hněvošice",
  "Hnojník",
  "Holasovice",
  "Horní Benešov",
  "Horní Bludovice",
  "Horní Město",
  "Horní Suchá",
  "Horní Těrlicko",
  "Hrabyně",
  "Hrádek",
  "Jakartovice",
  "Jeseník nad Odrou",
  "Jindřichov",
  "Jistebník",
  "Karlovice",
  "Karviná",
  "Kobeřice",
  "Komorní Lhotka",
  "Kopřivnice",
  "Kozlovice",
  "Kravaře",
  "Krmelín",
  "Kunčice pod Ondřejníkem",
  "Kunín",
  "Lichnov",
  "Lichnov (o. Nový Jičín)",
  "Lučina",
  "Ludgeřovice",
  "Město Albrechtice",
  "Metylovice",
  "Milíkov",
  "Mokré Lazce",
  "Morávka",
  "Mořkov",
  "Návsí u Jablunkova",
  "Nový Jičín",
  "Nýdek",
  "Oldřišov",
  "Orlová",
  "Osoblaha",
  "Ostravice",
  "Otice",
  "Paskov",
  "Petrovice u Karviné",
  "Petřvald",
  "Písek",
  "Píšť",
  "Pražmo",
  "Příbor",
  "Pustá Polom",
  "Raškovice",
  "Řepiště",
  "Ropice",
  "Rybí",
  "Rýmařov",
  "Sedliště",
  "Sedlnice",
  "Šenov",
  "Šilheřovice",
  "Slavkov",
  "Stará Ves nad Ondřejnicí",
  "Staré Město",
  "Staříč",
  "Starý Bohumín",
  "Starý Jičín",
  "Stěbořice",
  "Štěpánkovice",
  "Štítina",
  "Stonava",
  "Štramberk",
  "Studénka",
  "Tichá",
  "Třinec",
  "Trojanovice",
  "Václavovice",
  "Velká Polom",
  "Velké Heraltice",
  "Velké Hoštice",
  "Vendryně",
  "Veřovice",
  "Vítkov",
  "Vlčnov",
  "Vrbno pod Pradědem",
  "Vřesina",
  "Zátor",
  "Bedihošť",
  "Bělotín",
  "Bílá Lhota",
  "Bohuňovice",
  "Bouzov",
  "Brodek u Přerova",
  "Čelechovice na Hané",
  "Červenka",
  "Česká Ves",
  "Dolní Bohdíkov",
  "Dolní Studénky",
  "Dolní Újezd",
  "Doloplazy",
  "Drahanovice",
  "Dřevohostice",
  "Dub nad Moravou",
  "Grygov",
  "Hanušovice",
  "Hlubočky",
  "Hněvotín",
  "Horka nad Moravou",
  "Horní Moštěnice",
  "Horní Štěpánov",
  "Hustopeče Nad Bečvou",
  "Javorník",
  "Jeseník",
  "Kojetín",
  "Kokory",
  "Kostelec na Hané",
  "Kralice na Hané",
  "Leština",
  "Lipník nad Bečvou",
  "Loštice",
  "Loučná nad Desnou",
  "Lutín",
  "Majetín",
  "Medlov",
  "Město Libavá",
  "Moravičany",
  "Moravský Beroun",
  "Mostkovice",
  "Náklo",
  "Náměšť na Hané",
  "Němčice nad Hanou",
  "Nový Malín",
  "Olšany",
  "Osek nad Bečvou",
  "Oskava",
  "Otaslavice",
  "Paseka",
  "Písečná",
  "Plumlov",
  "Postřelmov",
  "Potštát",
  "Přáslavice",
  "Přemyslovice",
  "Přerov",
  "Příkazy",
  "Prostějov",
  "Protivanov",
  "Ptení",
  "Radslavice",
  "Rapotín",
  "Samotíšky",
  "Senice na Hané",
  "Skrbeň",
  "Slatinice",
  "Smržice",
  "Sobotín",
  "Štěpánov",
  "Šternberk",
  "Štíty",
  "Strážná",
  "Šumperk",
  "Těšetice",
  "Tovačov",
  "Troubelice",
  "Troubky",
  "Tršice",
  "Újezd",
  "Uničov",
  "Určice",
  "Úsov",
  "Vápenná",
  "Velká Bystřice",
  "Velké Losiny",
  "Velký Týnec",
  "Velký Újezd",
  "Věrovany",
  "Vidnava",
  "Vikýřovice",
  "Vrbátky",
  "Zábřeh",
  "Zlaté Hory",
  "Žulová",
  "Brandýs nad Orlicí",
  "Březová nad Svitavou",
  "Brněnec",
  "Býšť",
  "Bystré",
  "Bystřec",
  "Červená Voda",
  "Česká Třebová",
  "Choceň",
  "Chvaletice",
  "Dašice",
  "Dlouhá Třebová",
  "Dolní Čermná",
  "Dolní Dobrouč",
  "Dolní Roveň",
  "Dolní Sloupnice",
  "Heřmanův Městec",
  "Horní Čermná",
  "Horní Jelení",
  "Horní Sloupnice",
  "Hradec nad Svitavou",
  "Hrochův Týnec",
  "Jablonné nad Orlicí",
  "Jaroměřice",
  "Jedlová",
  "Jevíčko",
  "Králíky",
  "Kunčina",
  "Kunvald",
  "Lanškroun",
  "Lázně Bohdaneč",
  "Litomyšl",
  "Lukavice",
  "Luže",
  "Městečko Trnávka",
  "Miřetice",
  "Moravany",
  "Moravská Třebová",
  "Opatov",
  "Osík",
  "Polička",
  "Pomezí",
  "Prachovice",
  "Přelouč",
  "Proseč",
  "Radiměř",
  "Řečany nad Labem",
  "Rybitví",
  "Seč",
  "Skuteč",
  "Slatiňany",
  "Staré Hradiště",
  "Třemošnice",
  "Ústí nad Orlicí",
  "Vysoké Mýto",
  "Žamberk",
  "Bělá nad Radbuzou",
  "Bezdružice",
  "Blížejov",
  "Břasy",
  "Černošín",
  "Chlumčany",
  "Chodová Planá",
  "Chotěšov",
  "Chrást",
  "Dobřany",
  "Dobřív",
  "Domažlice",
  "Dýšina",
  "Hartmanice",
  "Heřmanova Huť",
  "Holýšov",
  "Horažďovice",
  "Horní Bříza",
  "Horšovský Týn",
  "Hostouň",
  "Hromnice",
  "Janovice nad Úhlavou",
  "Kasejovice",
  "Kašperské Hory",
  "Kaznějov",
  "Kdyně",
  "Kladruby",
  "Klenčí pod Čerchovem",
  "Kolinec",
  "Kout na Šumavě",
  "Kožlany",
  "Líně",
  "Manětín",
  "Měčín",
  "Meclov",
  "Město Touškov",
  "Mirošov",
  "Mrákov",
  "Mýto",
  "Nepomuk",
  "Nezvěstice",
  "Nýřany",
  "Nýrsko",
  "Planá",
  "Plánice",
  "Plasy",
  "Poběžovice",
  "Postřekov",
  "Přeštice",
  "Přimda",
  "Spálené Poříčí",
  "Šťáhlavy",
  "Staňkov",
  "Starý Plzenec",
  "Štěnovice",
  "Strašice",
  "Stráž",
  "Strážov",
  "Stříbro",
  "Sušice",
  "Švihov",
  "Tlučná",
  "Třemošná",
  "Vejprnice",
  "Všeruby",
  "Zbiroh",
  "Zbůch",
  "Železná Ruda",
  "Žihle",
  "Braník",
  "Černý Most",
  "Dolní Počernice",
  "Hodkovičky",
  "Horní Počernice",
  "Hostavice",
  "Karlín",
  "Letňany",
  "Libeň",
  "Malá Strana",
  "Modřany",
  "Praha",
  "Prosek",
  "Satalice",
  "Střížkov",
  "Vysehrad",
  "Vysočany",
  "Bavorov",
  "Bechyně",
  "Benešov nad Černou",
  "Blatná",
  "Borek",
  "Borová Lada",
  "Brloh",
  "České Budějovice",
  "České Velenice",
  "Český Krumlov",
  "Český Rudolec",
  "Chlum u Třeboně",
  "Chvalšiny",
  "Chýnov",
  "Chyšky",
  "Čimelice",
  "Čkyně",
  "Dačice",
  "Dolní Bukovsko",
  "Dolní Dvořiště",
  "Dřiteň",
  "Dubné",
  "Frymburk",
  "Hluboká nad Vltavou",
  "Horní Planá",
  "Horní Stropnice",
  "Hrdějovice",
  "Husinec",
  "Jarošov nad Nežárkou",
  "Jindřichův Hradec",
  "Jistebnice",
  "Kájov",
  "Kamenný Újezd",
  "Kardašova Řečice",
  "Katovice",
  "Kovářov",
  "Křemže",
  "Kunžak",
  "Ledenice",
  "Lhenice",
  "Lišov",
  "Litvínovice",
  "Lomnice nad Lužnicí",
  "Loučovice",
  "Malonty",
  "Malšice",
  "Mirotice",
  "Mirovice",
  "Mladá Vožice",
  "Netolice",
  "Nová Bystřice",
  "Nová Včelnice",
  "Nové Hrady",
  "Opařany",
  "Planá nad Lužnicí",
  "Protivín",
  "Radomyšl",
  "Sedlice",
  "Sepekov",
  "Ševětín",
  "Sezimovo Ústí",
  "Soběslav",
  "Srubec",
  "Stachy",
  "Strmilov",
  "Strunkovice nad Blanicí",
  "Studená",
  "Suchdol nad Lužnicí",
  "Tábor",
  "Třeboň",
  "Trhové Sviny",
  "Týn nad Vltavou",
  "Vacov",
  "Včelná",
  "Velešín",
  "Veselí nad Lužnicí",
  "Větřní",
  "Vlachovo Březí",
  "Vodňany",
  "Volary",
  "Volyně",
  "Vyšší Brod",
  "Zdíkov",
  "Bílovice nad Svitavou",
  "Blažovice",
  "Blížkovice",
  "Blučina",
  "Bořetice",
  "Bořitov",
  "Bošovice",
  "Božice",
  "Břeclav",
  "Březí",
  "Bučovice",
  "Bzenec",
  "Čebín",
  "Čejč",
  "Čejkovice",
  "Černá Hora",
  "Dambořice",
  "Dobšice",
  "Dolní Bojanovice",
  "Dolní Dunajovice",
  "Dolní Kounice",
  "Dolní Loućky",
  "Domanín",
  "Doubravice nad Svitavou",
  "Drásov",
  "Drnholec",
  "Dubňany",
  "Hevlín",
  "Hlohovec",
  "Hodonice",
  "Hodonín",
  "Hostěradice",
  "Hroznová Lhota",
  "Hrušky",
  "Hrušovany nad Jevišovkou",
  "Hrušovany u Brna",
  "Hustopeče",
  "Ivančice",
  "Ivanovice na Hané",
  "Jevišovice",
  "Kněždub",
  "Kobylí",
  "Křenovice",
  "Křepice",
  "Krumvíř",
  "Kunštát",
  "Kuřim",
  "Lanžhot",
  "Lelekovice",
  "Letonice",
  "Lipov",
  "Lipovec",
  "Lipůvka",
  "Louka",
  "Lužice",
  "Měnín",
  "Město Brno",
  "Mikulčice",
  "Modřice",
  "Mokrá Hora",
  "Moravská Nová Ves",
  "Moravský Krumlov",
  "Moravský Písek",
  "Moravský Žižkov",
  "Moutnice",
  "Mutěnice",
  "Nedvědice",
  "Nosislav",
  "Olbramovice",
  "Olešnice",
  "Ořechov",
  "Petrov",
  "Podivín",
  "Podolí",
  "Pohořelice",
  "Pozořice",
  "Předklášteří",
  "Prušánky",
  "Pustiměř",
  "Rájec-Jestřebí",
  "Ráječko",
  "Rajhrad",
  "Rajhradice",
  "Rakvice",
  "Ratíškovice",
  "Rohatec",
  "Rousínov",
  "Šakvice",
  "Šanov",
  "Šardice",
  "Šatov",
  "Šitbořice",
  "Šlapanice",
  "Sokolnice",
  "Strážnice",
  "Střelice",
  "Suchohrdly",
  "Sudoměřice",
  "Svitávka",
  "Tasovice",
  "Těšany",
  "Tišnov",
  "Troubsko",
  "Tvarožná",
  "Týnec",
  "Únanov",
  "Velká nad Veličkou",
  "Velké Bílovice",
  "Velké Němčice",
  "Velké Opatovice",
  "Velké Pavlovice",
  "Veselí nad Moravou",
  "Veverská Bítýška",
  "Viničné Šumice",
  "Višňové",
  "Vlkoš",
  "Vnorovy",
  "Vranovice",
  "Vrbovec",
  "Vyškov",
  "Žabčice",
  "Zaječí",
  "Zastávka",
  "Zbraslav",
  "Zbýšov",
  "Ždánice",
  "Želešice",
  "Žeravice",
  "Židlochovice",
  "Bechlín",
  "Bečov",
  "Benešov nad Ploučnicí",
  "Bílina",
  "Bílina Kyselka",
  "Bohušovice nad Ohří",
  "Braňany",
  "Březno",
  "Budyně nad Ohří",
  "Bystřany",
  "Černčice",
  "Česká Kamenice",
  "Chabařovice",
  "Chřibská",
  "Čížkovice",
  "Děčín",
  "Dobroměřice",
  "Dolní Podluží",
  "Dolní Poustevna",
  "Dubí",
  "Horní Jiřetín",
  "Hošťka",
  "Hrob",
  "Jílové",
  "Jiříkov",
  "Kadaň",
  "Klášterec nad Ohří",
  "Košťany",
  "Kovářská",
  "Krásná Lípa",
  "Křešice",
  "Kryry",
  "Lenešice",
  "Liběšice",
  "Libochovice",
  "Libouchec",
  "Litoměřice",
  "Litvínov",
  "Lom u Mostu",
  "Měcholupy",
  "Meziboři",
  "Mikulášovice",
  "Novosedlice",
  "Obrnice",
  "Perštejn",
  "Peruc",
  "Podbořany",
  "Povrly",
  "Proboštov",
  "Radonice",
  "Řehlovice",
  "Rumburk",
  "Šluknov",
  "Staré Křečany",
  "Štětí",
  "Terezín",
  "Třebenice",
  "Údlice",
  "Úštěk",
  "Vejprty",
  "Velemín",
  "Velké Březno",
  "Velký Šenov",
  "Verneřice",
  "Vilémov",
  "Vroutek",
  "Zabrušany",
  "Žatec",
  "Žitenice",
  "Bohdalov",
  "Budišov",
  "Bystřice nad Pernštejnem",
  "Černovice",
  "Chotěboř",
  "Dobronín",
  "Dolní Cerekev",
  "Golčův Jeníkov",
  "Habry",
  "Havlíčkův Brod",
  "Herálec",
  "Horní Cerekev",
  "Hrotovice",
  "Jaroměřice nad Rokytnou",
  "Jemnice",
  "Jimramov",
  "Kamenice nad Lipou",
  "Kněžice",
  "Křižanov",
  "Křížová",
  "Ledeč nad Sázavou",
  "Lípa",
  "Luka nad Jihlavou",
  "Lukavec",
  "Měřín",
  "Mohelno",
  "Moravské Budějovice",
  "Náměšť nad Oslavou",
  "Nová Cerekev",
  "Nové Město na Moravě",
  "Nové Syrovice",
  "Nové Veselí",
  "Okříšky",
  "Okrouhlice",
  "Pelhřimov",
  "Počátky",
  "Polná",
  "Přibyslav",
  "Rouchovany",
  "Stařeč",
  "Štoky",
  "Světlá nad Sázavou",
  "Svratka",
  "Telč",
  "Třebíč",
  "Třešť",
  "Velká Bíteš",
  "Velké Meziříčí",
  "Velký Beranov",
  "Žďár nad Sázavou",
  "Žďár nad Sázavou Druhy",
  "Želetava",
  "Želiv",
  "Žirovnice",
  "Bánov",
  "Bílovice",
  "Boršice",
  "Březolupy",
  "Buchlovice",
  "Bystřice pod Hostýnem",
  "Chropyně",
  "Chvalčov",
  "Dolní Bečva",
  "Dolní Němčí",
  "Fryšták",
  "Halenkovice",
  "Hluk",
  "Holešov",
  "Horní Bečva",
  "Horní Lideč",
  "Hošťálková",
  "Hovězí",
  "Hulín",
  "Hvozdná",
  "Jablůnka",
  "Jalubí",
  "Karolinka",
  "Kelč",
  "Kněžpole",
  "Koryčany",
  "Kroměříž",
  "Kvasice",
  "Lešná",
  "Lidečko",
  "Liptál",
  "Luhačovice",
  "Mistřice",
  "Nedašov",
  "Nový Hrozenkov",
  "Ostrožská Lhota",
  "Ostrožská Nová Ves",
  "Polešovice",
  "Popovice",
  "Pozlovice",
  "Prostřední Bečva",
  "Prusinovice",
  "Ratiboř",
  "Rožnov pod Radhoštěm",
  "Slavičín",
  "Slušovice",
  "Spytihněv",
  "Štítná nad Vláří",
  "Strání",
  "Suchá Loz",
  "Šumice",
  "Tečovice",
  "Tlumačov",
  "Topolná",
  "Traplice",
  "Trnava",
  "Uherské Hradiště",
  "Uherský Brod",
  "Uherský Ostroh",
  "Valašská Bystřice",
  "Valašská Polanka",
  "Valašské Klobouky",
  "Valašské Meziříčí",
  "Velké Karlovice",
  "Vidče",
  "Všemina",
  "Vsetín",
  "Záhorovice",
  "Zašová",
  "Zlechov",
  "Zlín",
  "Žlutava",
  "Zubří",
];
